# Generated by Django 4.0.3 on 2022-04-03 03:41

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_ruta_caracteristicas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruta',
            name='caracteristicas',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
