# Generated by Django 4.0.3 on 2022-04-10 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_urbana'),
    ]

    operations = [
        migrations.AddField(
            model_name='mtb',
            name='imagen_mtb',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='ruta',
            name='imagen_ruta',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='urbana',
            name='imagen_urbana',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
