# Generated by Django 4.0.3 on 2022-04-10 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_mtb_imagen_mtb_ruta_imagen_ruta_urbana_imagen_urbana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruta',
            name='imagen_ruta',
            field=models.ImageField(blank=True, null=True, upload_to='bikes'),
        ),
    ]
