# Generated by Django 4.0.3 on 2022-04-10 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_alter_ruta_imagen_ruta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruta',
            name='imagen_ruta',
            field=models.ImageField(blank=True, null=True, upload_to='bikes/'),
        ),
    ]
