# Generated by Django 4.0.3 on 2022-04-10 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0010_alter_ruta_imagen_ruta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ruta',
            old_name='imagen_ruta',
            new_name='imagenRuta',
        ),
    ]
