# Generated by Django 4.0.3 on 2022-04-10 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0011_rename_imagen_ruta_ruta_imagenruta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ruta',
            old_name='imagenRuta',
            new_name='imagen_ruta',
        ),
    ]
